package edu.umn.csci5801.model;

public enum Milestone {
      PRELIM_COMMITTEE_APPOINTED, WRITTEN_PE_SUBMITTED, WRITTEN_PE_APPROVED, ORAL_PE_PASSED, DPF_SUBMITTED, DPF_APPROVED, THESIS_COMMITTEE_APPOINTED, PROPOSAL_PASSED, GRADUATION_PACKET_REQUESTED, THESIS_SUBMITTED, THESIS_APPROVED, DEFENSE_PASSED, PROJECT_COMMITTEE_APPOINTED, TRACKING_FORM_SUBMITTED, TRACKING_FORM_APPROVED
}

